version: '3'

services:
  # Node.js application

  attacker_app:
    build: ./attacker_app
    ports:
      - "3005:3005"

  app:
    build: ./legit_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  # MongoDB
  mongo:
    image: mongo
    ports:
      - "27017:27017"
