version: '3'

services:
  # Node.js application
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  # MongoDB
  mongo:
    image: mongo
    ports:
      - "27017:27017"
